### ISSUE TITLE
Support for Python 3

### ISSUE THREAD

**Issue by hrxn** [ericpruitt/mimesort#1]
Hello,

although this project hasn't seen a commit in a while, it's still the best I could find on all of GitHub.
So, Kudos to you!

I've only been using it for a short while, but it works really great so far, even on Windows.

What do you think about porting to Python 3?
That is actively developed, all efforts in improvement go there, and it's what they [recommend](https://wiki.python.org/moin/Python2orPython3) to use.

Lack of Python 3 support is getting more relevant, I'd say, especially on platforms where most users only have Python 3, like the aforementioned Windows, for example.

Anyway, I would like to hear your opinion on this matter.

Kind regards

**Comment by ericpruitt** [comment]
Anything I write these days targets Python 3 first and sometimes Python 2.7 depending on where and how the tool is going to be used. I actually considered porting mimesort to Python 3 a couple of years or so ago. I don't remember the exact details, but I think I ran into some problems with the "magic" module having poor handling of character encodings which effectively made the mimesort almost useless for me because I have lots of files that use non-ASCII characters. Python 2 is still installed by default on the Linux distributions I use, and there aren't any other features I've wanted to add to mimesort, so I haven't been particularly motivated to spend time porting an otherwise functional tool. Maybe I overlooked some previously or perhaps the issues in the magic module have been resolved, so I'll do some poking around and follow-up with you within a couple of days.

Thanks for the kind words, and I'm glad to hear you've found to tool useful.

**Comment by ericpruitt** [comment]
It turns out I still had the Python 3 changes I was experimenting with which saved me a little of bit of work. I did recall the problem correctly in that python3-magic does not accept surrogate pairs and will effectively reject anything that isn't valid UTF-8. After looking at the source code of the python3-magic library, I discovered that I can easily just create a new class that inherits from the existing class but replaces the problematic function with a version that works. I will update this issue once I've pushed the changes for Python 3.

**Comment by ericpruitt** [comment]
@Hrxn , you mentioned that this script works on Windows -- which magic number library are you using on Windows including the version number?

**Comment by hrxn** [comment]
I haven't used any magic library so far, to be honest, only the `-m` option.

But I think these should work: https://github.com/pidydx/libmagicwin64

**Comment by ericpruitt** [comment]
I don't have Windows development environment setup right now, and I'm not interested in making one just for this script. When I looked at the code for the magic library I have installed, it didn't look as though it supported Windows. I asked because if one of the magic libraries I already support simply _happened_ to work on Windows simply as a nice side effect, I was just going to make sure to test my changes with it (but on Linux).

If you're not using a magic number library, about the only thing preventing this script from being run Python 3 are the print statements and some of the dictionary iterations that could be probably be replaced by even a novice Python programmer (I don't know what your actual level of experience is).

**Comment by hrxn** [comment]
> I don't have Windows development environment setup right now, and I'm not interested in making one just for this script. [..]

Sure, I can do the testing on Windows.

> If you're not using a magic number library, about the only thing preventing this script from being run Python 3 are the print statements and some of the dictionary iterations that could be probably be replaced by even a novice Python programmer (I don't know what your actual level of experience is).

With Python, basically no experience. I'm also not a programmer by trade, but I can usually figure these things out. I'll be on vacation for some days now, but when I'm back I will test it with my freshly installed Python 3.6.0.

**Comment by ericpruitt** [comment]
I have added support for Python 3 in ac929881ea09931b9057bfca72a6015b04d458f0. Please let me know if you have any problems with it.

**Comment by hrxn** [comment]
Okay, I just tested this. Sorry for being so late, I made a note, but must have missed it somehow.

OS: Microsoft Windows 10 x64 [Version 10.0.14393]
Python:
```
F:\Tools\Test>Python
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```
And here is what I got:
```
F:\Tools\Test>python D:\Src\mimesort-master\mimesort.py
Traceback (most recent call last):
  File "D:\Src\mimesort-master\mimesort.py", line 266, in <module>
    main()
  File "D:\Src\mimesort-master\mimesort.py", line 252, in main
    response = raw_input('Sort %s? [N/y] ' % os.getcwd())
NameError: name 'raw_input' is not defined

F:\Tools\Test>
```

**Comment by ericpruitt** [comment]
Fixed and pushed. When I tested this, I used an explicit folder which bypassed the prompt. There's technically still a few things that need to be changed to properly handle the Unicode / bytes changes in Python 3, but I think at least some of those issues are less likely to be a problem on Windows.

**Comment by hrxn** [comment]
```
F:\Tools\Test>python D:\Src\mimesort-master\mimesort.py
Sort F:\Tools\Test? [N/y] y
```

A lot better now. Thanks! 😉 
Sorting files now as well.

Please let me know if there is anything else I should test..
